# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bup < Formula
  desc "Back UP CLI written in Go."
  homepage "https://github.com/smashedr/bup"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/bup/releases/download/1.0.2/bup_Darwin_x86_64.tar.gz"
      sha256 "8aee4be6ef47136a3915217080bf41f1760305aa15efc6c1ab24d7b7a03e4b1a"

      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/bup/releases/download/1.0.2/bup_Darwin_arm64.tar.gz"
      sha256 "683d8f8ece01b0ceaf442111a3d0643ed9ef01bd47378a2ce844515c811d7e2f"

      def install
        bin.install "bup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.2/bup_Linux_x86_64.tar.gz"
      sha256 "64995ad84b3ced8221e7faf70129657590514afcbcbd08ee2dc113471d036a1e"
      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.2/bup_Linux_arm64.tar.gz"
      sha256 "4353448249a89a6d489e0f4a67b201e97aca0d6b3d91112be8eec791ec57e538"
      def install
        bin.install "bup"
      end
    end
  end
end
