# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallRelease < Formula
  desc "CLI to Install a GitHub Release"
  homepage "https://smashedr.github.io/ir"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/install-release/releases/download/0.0.7/ir_Darwin_x86_64.tar.gz"
      sha256 "cc00a7d61816a0ef078fcf5d2f97a1a86d88bb7258c8d12a1d2d9c316f09e564"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/install-release/releases/download/0.0.7/ir_Darwin_arm64.tar.gz"
      sha256 "6554091a71aff9d20f9890577fc1d25390c0e736840ab7eb2946b153a3bbb3af"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.7/ir_Linux_x86_64.tar.gz"
      sha256 "35597c056e096205716ae29bf3ff7651c3b978680add6973935b5fc6c10fae65"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.7/ir_Linux_arm64.tar.gz"
      sha256 "cb2dfb64607a7be8f9cfcf9f87b008c2536cc1ba9d6fe98bab59ff0f9fc35956"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/install-release/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/install-release -V")
  end
end
