# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallRelease < Formula
  desc "CLI to Install a GitHub Release"
  homepage "https://smashedr.github.io/install-release"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/install-release/releases/download/0.0.12/ir_Darwin_x86_64.tar.gz"
      sha256 "5670478cabec978133741f9ae48a91b939213e67dfe9aec3cd6e02f5e46c8a8e"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/install-release/releases/download/0.0.12/ir_Darwin_arm64.tar.gz"
      sha256 "4c06743d06a10951bf4fb6183907339d1dd05840cb9e3afceaf4879d88c8e509"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.12/ir_Linux_x86_64.tar.gz"
      sha256 "1dd983c61d5dff91ba338bdcd8370f324c547a000ba87d72c66edbe9b4ee2748"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.12/ir_Linux_arm64.tar.gz"
      sha256 "39748f59deaf50708fb20c2dd0aa3ad6f4bc3ec325586aa27642263806d83e9a"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/install-release/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/install-release -V")
  end
end
