# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ir < Formula
  desc "CLI to Install a GitHub Release"
  homepage "https://github.com/smashedr/ir"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/install-release/releases/download/0.0.2/ir_Darwin_x86_64.tar.gz"
      sha256 "0e8b4a83106289cd4d3dac3b2689ff7e467234077b0660ea383af4f492f5ed5e"

      def install
        bin.install "ir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/install-release/releases/download/0.0.2/ir_Darwin_arm64.tar.gz"
      sha256 "e1a64285408ce02e016d18550fa588cd222d18bdaf5ee871af65f28f89f012d3"

      def install
        bin.install "ir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.2/ir_Linux_x86_64.tar.gz"
      sha256 "57f0a526f135a4bdf6d5590d6b919241657102bb295780d1b06a1a9f89f17ac8"
      def install
        bin.install "ir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.2/ir_Linux_arm64.tar.gz"
      sha256 "63ee7ed56717fd9df8fed651c2761e5bb22c0a994d28264516894cb96a46e983"
      def install
        bin.install "ir"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/install-release/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/install-release -V")
  end
end
