# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallRelease < Formula
  desc "CLI to Install a GitHub Release"
  homepage "https://github.com/smashedr/install-release"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/install-release/releases/download/0.0.1/install-release_Darwin_x86_64.tar.gz"
      sha256 "5a58642c30d822246be562d41d070a313ebacb31a7e2f7d9df1bd625ee817aa7"

      def install
        bin.install "install-release"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/install-release/releases/download/0.0.1/install-release_Darwin_arm64.tar.gz"
      sha256 "8fec5a7f8e15a33c21e83e1c840ca4b96ffdc6bff437bef6e709121cf9879426"

      def install
        bin.install "install-release"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.1/install-release_Linux_x86_64.tar.gz"
      sha256 "ce53c556430ebeeb6f8ae3eee77b1989a069e52748d2f1c542020ea53310944f"
      def install
        bin.install "install-release"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.1/install-release_Linux_arm64.tar.gz"
      sha256 "8a45d87ae5c439daaf2303c2f0cc59de9dd0f65211ef1c0d557f11e5ee2e3183"
      def install
        bin.install "install-release"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/install-release/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/install-release -V")
  end
end
